### ISSUE TITLE
Projects fails to build on Fedora 25 using vscode

### ISSUE THREAD

**Issue by bhkeys** [bernardbr/hello-world-netcore#1]
I get these errors upon build

![build error](http://pix.toile-libre.org/upload/original/1496159636.png)

Okay, so then I click to show problems, then I get this

![no problems](http://pix.toile-libre.org/upload/original/1496159577.png)

**Comment by bernardbr** [comment]
Did you do ```dotnet restore``` before trying to debug?

**Comment by bhkeys** [comment]
I just ran those and it said
```warn : The folder '/home/bkeys/Devel/hello-world-netcore/src/consoleApp' does not contain a project to restore.```

I did it in the project root as well

```warn : The folder '/home/bkeys/Devel/hello-world-netcore/' does not contain a project to restore.```

**Comment by bernardbr** [comment]
Could you give me your ```dotnet --info```?

**Comment by bhkeys** [comment]
```
[bkeys@localhost hello-world-netcore]$ dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003175)

Product Information:
 Version:            1.0.0-preview2-1-003175
 Commit SHA-1 hash:  bb053ed000

Runtime Environment:
 OS Name:     fedora
 OS Version:  25
 OS Platform: Linux
 RID:         fedora.25-x64
```

**Comment by bernardbr** [comment]
I'm closing it because this issue is tracked by https://github.com/OmniSharp/omnisharp-vscode/issues/1526#issuecomment-304927990
